/mnt/a/GitHub/WorkingDogs/Blue/Linux64DN8AOTU24/Blue
/mnt/a/GitHub/WorkingDogs/Blue/Linux64DN8FDU24/Blue
/mnt/a/GitHub/WorkingDogs/BuildFilter/Linux64DN8AOTU24/BuildFilter
/mnt/a/GitHub/WorkingDogs/BuildFilter/Linux64DN8FDU24/BuildFilter
/mnt/a/GitHub/WorkingDogs/CondenseProkkaTbl/Linux64DN8AOTU24/CondenseProkkaTbl
/mnt/a/GitHub/WorkingDogs/CondenseProkkaTbl/Linux64DN8FDU24/CondenseProkkaTbl
/mnt/a/GitHub/WorkingDogs/ExtractHeadersFromFasta/Linux64DN8AOTU24/ExtractHeadersFromFasta
/mnt/a/GitHub/WorkingDogs/ExtractHeadersFromFasta/Linux64DN8FDU24/ExtractHeadersFromFasta
/mnt/a/GitHub/WorkingDogs/FilterReads/Linux64DN8AOTU24/FilterReads
/mnt/a/GitHub/WorkingDogs/FilterReads/Linux64DN8FDU24/FilterReads
/mnt/a/GitHub/WorkingDogs/Kelpie_v2/Linux64DN8AOTU24/Kelpie_v2
/mnt/a/GitHub/WorkingDogs/Kelpie_v2/Linux64DN8FDU24/Kelpie_v2
/mnt/a/GitHub/WorkingDogs/Tessel/Linux64DN8AOTU24/Tessel
/mnt/a/GitHub/WorkingDogs/Tessel/Linux64DN8FDU24/Tessel

/mnt/a/GitHub/WorkingDogs/Blue/Linux64DN8AOTU20/Blue
/mnt/a/GitHub/WorkingDogs/Blue/Linux64DN8FDU20/Blue
/mnt/a/GitHub/WorkingDogs/BuildFilter/Linux64DN8AOTU20/BuildFilter
/mnt/a/GitHub/WorkingDogs/BuildFilter/Linux64DN8FDU20/BuildFilter
/mnt/a/GitHub/WorkingDogs/CondenseProkkaTbl/Linux64DN8AOTU20/CondenseProkkaTbl
/mnt/a/GitHub/WorkingDogs/CondenseProkkaTbl/Linux64DN8FDU20/CondenseProkkaTbl
/mnt/a/GitHub/WorkingDogs/ExtractHeadersFromFasta/Linux64DN8AOTU20/ExtractHeadersFromFasta
/mnt/a/GitHub/WorkingDogs/ExtractHeadersFromFasta/Linux64DN8FDU20/ExtractHeadersFromFasta
/mnt/a/GitHub/WorkingDogs/FilterReads/Linux64DN8AOTU20/FilterReads
/mnt/a/GitHub/WorkingDogs/FilterReads/Linux64DN8FDU20/FilterReads
/mnt/a/GitHub/WorkingDogs/Kelpie_v2/Linux64DN8AOTU20/Kelpie_v2
/mnt/a/GitHub/WorkingDogs/Kelpie_v2/Linux64DN8FDU20/Kelpie_v2
/mnt/a/GitHub/WorkingDogs/Tessel/Linux64DN8AOTU20/Tessel
/mnt/a/GitHub/WorkingDogs/Tessel/Linux64DN8FDU20/Tessel
