<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\WorkingDogsCoreLibrary\kMerCollections.cs">
      <Link>kMerCollections.cs</Link>
    </Compile>
    <Compile Include="..\..\WorkingDogsCoreLibrary\kMers.cs">
      <Link>kMers.cs</Link>
    </Compile>
    <Compile Include="..\..\WorkingDogsCoreLibrary\SeqFiles.cs">
      <Link>SeqFiles.cs</Link>
    </Compile>
    <Compile Include="..\..\WorkingDogsCoreLibrary\Sequence.cs">
      <Link>Sequence.cs</Link>
    </Compile>
  </ItemGroup>
</Project>